require('./validate.test.js');
require('./validators.tm2z.test.js');
require('./validators.tilejson.test.js');
require('./validators.serialtiles.test.js');
require('./validators.omnivore.test.js');
require('./full.validation.tm2z.js');
require('./full.validation.tilejson.js');
require('./full.validation.serialtiles.js');
require('./full.validation.omnivore.js');
